#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-ttystatus
Version  : 0.23.orig
Release  : 9
URL      : http://code.liw.fi/debian/pool/main/p/python-ttystatus/python-ttystatus_0.23.orig.tar.gz
Source0  : http://code.liw.fi/debian/pool/main/p/python-ttystatus/python-ttystatus_0.23.orig.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: python-ttystatus-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
Progress and status updates on terminals
========================================

%package python
Summary: python components for the python-ttystatus package.
Group: Default

%description python
python components for the python-ttystatus package.


%prep
%setup -q -n ttystatus-0.23

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
